### ISSUE TITLE
[REQUEST] Upload to an account

### ISSUE THREAD

**Issue by GUUser91** [FayasNoushad/Pixeldrain#13]
Account support would be nice, thanks

**Comment by zedeska** [comment]
Yes that would be very nice

**Comment by zedeska** [comment]
Okay I have made some tweaks to the original script to be able to upload to an account.

`import requests
import base64

temp_api = ":'YOUR API KEY'"
tapi_byte = temp_api.encode("ascii")

base64_bytes = base64.b64encode(tapi_byte)
api = base64_bytes.decode("ascii")

def upload_file(file):
    response = requests.post(
        "https://pixeldrain.com/api/file/",
        headers={"authorization": "Basic "+api},
        data={"anonymous": False},
        files={"file": open(file, "rb")}
    )
    return response.json()`

**Comment by FayasNoushad** [comment]
> Okay I have made some tweaks to the original script to be able to upload to an account.
> 
> ```python
> import requests
> import base64
> 
> def upload_file(file):
> 
>     temp_api = ":YOUR API KEY"
>     tapi_byte = temp_api.encode("ascii")
> 
>     base64_bytes = base64.b64encode(tapi_byte)
>     api = base64_bytes.decode("ascii")
> 
>     response = requests.post(
>         "https://pixeldrain.com/api/file",
>         headers={"authorization": "Basic "+api},
>         data={"anonymous": False},
>         files={"file": open(file, "rb")}
>     )
>     return response.json()
> ```

Thanks for your code. But their API currently doesn't allow direct file uploads to account.

**Comment by zedeska** [comment]
no it does

**Comment by FayasNoushad** [comment]
> it does

How?
I checked, but I can't upload to my pixeldrain account with my api.
